app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

basket:
    resource: "@AppBundle/Resources/config/routing/basket.yml"
    prefix: /basket

order:
    resource: "@AppBundle/Resources/config/routing/order.yml"
    prefix: /order

orders:
    resource: "@AppBundle/Resources/config/routing/orders.yml"
    prefix: /orders

supplier:
    resource: "@AppBundle/Resources/config/routing/supplier.yml"
    prefix: /supplier

product:
    resource: "@AppBundle/Resources/config/routing/product.yml"
    prefix: /product

user:
    resource: "@AppBundle/Resources/config/routing/user.yml"
    prefix: /
