security:
    providers:
        codifico_user:
            id: codifico_user_provider

    encoders:
        AppBundle\Entity\User:
            algorithm:          sha512
            iterations:         5000

    role_hierarchy:
        ROLE_USER:      ~
        ROLE_ADMIN:     ROLE_USER

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        api:
            pattern:    ^/
            fos_oauth:  true
            stateless:  true
            anonymous:  false

    access_control:
        - { path: ^/product/$, roles: [ROLE_USER], methods: [GET]}
        - { path: ^/product, roles: [ ROLE_ADMIN ]}
        - { path: ^/order, roles: [ ROLE_ADMIN ]}
        - { path: ^/orders, roles: [ ROLE_ADMIN ]}
        - { path: ^/producent, roles: [ ROLE_ADMIN ]}
        - { path: ^/, roles: [ IS_AUTHENTICATED_FULLY ] }
