services:
    codifico_user_provider:
        class: %doctrine.orm.security.user.provider.class%
        arguments:
            - @doctrine
            - AppBundle:User
            - username

    controller.product:
        class: AppBundle\Controller\ProductController
        arguments:
            - @action.product.create
            - @action.product.update
            - @action.product.index
            - @action.product.remove

    controller.supplier:
        class: AppBundle\Controller\SupplierController
        arguments:
            - @action.supplier.create
            - @action.supplier.update
            - @action.supplier.index
            - @action.supplier.remove

    controller.basket:
        class: AppBundle\Controller\BasketController
        arguments:
            - @repository.basket
            - @repository.order
            - @repository.order_item
            - @form.factory
            - @=service('security.context').getToken().getUser()
            - @doctrine.orm.entity_manager

    controller.profile:
        class: AppBundle\Controller\UserController
        arguments:
            - @=service('security.context').getToken().getUser()

    controller.order:
        class: AppBundle\Controller\OrderController
        arguments:
            - @action.order.create
            - @action.order.update
            - @action.order.index
            - @action.order.remove
            - @action.order.activate
            - @action.order.current

    action.product.create:
        class: AppBundle\Actions\ProductCreateAction
        arguments:
            - @event_dispatcher
            - @repository.product
            - @form.factory
            - @form.type.product
        calls:
            - [ setRequestStack, [@request_stack]]

    action.product.update:
        class: AppBundle\Actions\ProductUpdateAction
        arguments:
            - @event_dispatcher
            - @form.factory
            - @form.type.product
        calls:
            - [ setRequestStack, [@request_stack]]

    action.product.index:
        class: AppBundle\Actions\ProductIndexAction
        arguments:
            - @repository.product

    action.product.remove:
        class: AppBundle\Actions\ProductRemoveAction
        arguments:
            - @event_dispatcher
            - @repository.product

    action.order.create:
        class: AppBundle\Actions\OrderCreateAction
        arguments:
            - @event_dispatcher
            - @repository.product
            - @form.factory
            - @form.type.order
        calls:
            - [ setRequestStack, [@request_stack]]

    action.order.update:
        class: AppBundle\Actions\OrderUpdateAction
        arguments:
            - @event_dispatcher
            - @form.factory
            - @form.type.order
        calls:
            - [ setRequestStack, [@request_stack]]

    action.order.index:
        class: AppBundle\Actions\OrderIndexAction
        arguments:
            - @repository.order

    action.order.remove:
        class: AppBundle\Actions\OrderRemoveAction
        arguments:
            - @event_dispatcher
            - @repository.order
            - @logger

    action.order.activate:
        class: AppBundle\Actions\OrderActivateAction
        arguments:
            - @repository.order

    action.order.current:
        class: AppBundle\Actions\OrderIndexCurrentAction
        arguments:
            - @repository.order
            - @repository.order_item

    action.supplier.create:
        class: AppBundle\Actions\SupplierCreateAction
        arguments:
            - @event_dispatcher
            - @repository.supplier
            - @form.factory
            - @form.type.supplier
        calls:
            - [ setRequestStack, [@request_stack]]

    action.supplier.update:
        class: AppBundle\Actions\SupplierUpdateAction
        arguments:
            - @event_dispatcher
            - @form.factory
            - @form.type.supplier
        calls:
            - [ setRequestStack, [@request_stack]]

    action.supplier.index:
        class: AppBundle\Actions\SupplierIndexAction
        arguments:
            - @repository.supplier

    action.supplier.remove:
        class: AppBundle\Actions\SupplierRemoveAction
        arguments:
            - @event_dispatcher
            - @repository.supplier

    listener.action:
        class: AppBundle\EventListener\DoctrineListener
        arguments:
            - @doctrine.orm.default_entity_manager
        tags:
            - { name: kernel.event_listener, event: action.create, method: onEntityCreate }
            - { name: kernel.event_listener, event: action.update, method: onEntityUpdate }
            - { name: kernel.event_listener, event: action.remove, method: onEntityRemove }

    listener.password:
        class: AppBundle\EventListener\PasswordListener
        arguments:
            - @security.password_encoder
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

    form.type.product:
        class: AppBundle\Form\ProductType
        arguments:
            - @doctrine.orm.entity_manager

    form.type.order:
        class: AppBundle\Form\OrderType
        arguments:
            - @doctrine.orm.entity_manager

    form.type.supplier:
        class: AppBundle\Form\SupplierType
        arguments:
            - @doctrine.orm.entity_manager

    repository.product:
        class: AppBundle\Entity\ProductRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - AppBundle\Entity\Product

    repository.supplier:
        class: AppBundle\Entity\SupplierRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - AppBundle\Entity\Supplier

    repository.basket:
        class: AppBundle\Entity\BasketRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - AppBundle\Entity\Basket

    repository.order:
        class: AppBundle\Entity\OrderRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - AppBundle\Entity\Order

    repository.order_item:
        class: AppBundle\Entity\OrderItemRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - AppBundle\Entity\OrderItem

    codifico_core.param_converter.query_criteria_converter:
        class: AppBundle\Request\ParamConverter\CriteriaParamConverter
        arguments:
            - @serializer
        tags:
            - { name: request.param_converter, converter: query_criteria_converter }

    param_converter.product:
        class: AppBundle\Request\ParamConverter\ProductParamConverter
        arguments:
            - @doctrine
        tags:
            - { name: request.param_converter, converter: product_converter, priority: 1 }

    param_converter.order:
        class: AppBundle\Request\ParamConverter\OrderParamConverter
        arguments:
            - @doctrine
        tags:
            - { name: request.param_converter, converter: order_converter, priority: 1 }

    param_converter.supplier:
        class: AppBundle\Request\ParamConverter\SupplierParamConverter
        arguments:
            - @doctrine
        tags:
            - { name: request.param_converter, converter: supplier_converter, priority: 1 }

