services:
    codifico_user_provider:
        class: %doctrine.orm.security.user.provider.class%
        arguments:
            - @doctrine
            - AppBundle:User
            - username

    codifico_user.password.listener:
        class: AppBundle\EventListener\PasswordListener
        arguments:
            - @security.password_encoder
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

    controller.product:
        class: AppBundle\Controller\ProductController
        arguments:
            - @repository.product

    controller.basket:
        class: AppBundle\Controller\BasketController
        arguments:
            - @repository.basket
            - @repository.order
            - @form.factory
            - @=service('security.context').getToken().getUser()
            - @doctrine.orm.entity_manager

    controller.profile:
        class: AppBundle\Controller\UserController
        arguments:
            - @=service('security.context').getToken().getUser()

    controller.order:
            class: AppBundle\Controller\OrderController
            arguments:
                - @repository.order
                - @repository.order_item

    repository.product:
        class: AppBundle\Entity\ProductRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - AppBundle\Entity\Product

    repository.basket:
        class: AppBundle\Entity\BasketRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - AppBundle\Entity\Basket

    repository.order:
        class: AppBundle\Entity\OrderRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - AppBundle\Entity\Order

    repository.order_item:
        class: AppBundle\Entity\OrderItemRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - AppBundle\Entity\OrderItem

    codifico_core.param_converter.query_criteria_converter:
        class: AppBundle\Request\ParamConverter\CriteriaParamConverter
        arguments:
            - @serializer
        tags:
            - { name: request.param_converter, converter: query_criteria_converter }
