services:
    codifico_user_provider:
        class: %doctrine.orm.security.user.provider.class%
        arguments:
            - @doctrine
            - AppBundle:User
            - username

    codifico_user.password.listener:
        class: AppBundle\EventListener\PasswordListener
        arguments:
            - @security.password_encoder
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

    controller.product:
        class: AppBundle\Controller\ProductController
        arguments:
            - @action.product.create
            - @action.product.update
            - @action.product.index
            - @action.product.remove
            - @doctrine.orm.default_entity_manager

    controller.producent:
        class: AppBundle\Controller\ProducentController
        arguments:
            - @repository.producent
            - @doctrine.orm.default_entity_manager
            - @form.factory

    controller.basket:
        class: AppBundle\Controller\BasketController
        arguments:
            - @repository.basket
            - @repository.order
            - @repository.order_item
            - @form.factory
            - @=service('security.context').getToken().getUser()
            - @doctrine.orm.entity_manager

    controller.profile:
        class: AppBundle\Controller\UserController
        arguments:
            - @=service('security.context').getToken().getUser()

    controller.order:
        class: AppBundle\Controller\OrderController
        arguments:
            - @repository.order
            - @repository.order_item

    controller.orders:
        class: AppBundle\Controller\OrdersController
        arguments:
            - @repository.order
            - @doctrine.orm.entity_manager
            - @form.factory
            - @logger

    action.product.create:
        class: AppBundle\Actions\ProductCreateAction
        arguments:
            - @repository.product
            - @form.factory
            - @form.type.product
        calls:
            - [ setRequestStack, [@request_stack]]
    action.product.update:
        class: AppBundle\Actions\ProductUpdateAction
        arguments:
            - @form.factory
            - @form.type.product
        calls:
            - [ setRequestStack, [@request_stack]]

    action.product.index:
        class: AppBundle\Actions\ProductIndexAction
        arguments:
            - @repository.product

    action.product.remove:
        class: AppBundle\Actions\ProductRemoveAction

    form.type.product:
        class: AppBundle\Form\ProductType
        arguments:
            - @doctrine.orm.entity_manager

    repository.product:
        class: AppBundle\Entity\ProductRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - AppBundle\Entity\Product

    repository.producent:
        class: AppBundle\Entity\ProducentRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - AppBundle\Entity\Producent

    repository.basket:
        class: AppBundle\Entity\BasketRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - AppBundle\Entity\Basket

    repository.order:
        class: AppBundle\Entity\OrderRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - AppBundle\Entity\Order

    repository.order_item:
        class: AppBundle\Entity\OrderItemRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - AppBundle\Entity\OrderItem

    codifico_core.param_converter.query_criteria_converter:
        class: AppBundle\Request\ParamConverter\CriteriaParamConverter
        arguments:
            - @serializer
        tags:
            - { name: request.param_converter, converter: query_criteria_converter }

    param_converter.product:
        class: AppBundle\Request\ParamConverter\ProductParamConverter
        arguments:
            - @doctrine
        tags:
            - { name: request.param_converter, converter: product_converter, priority: 1 }
