orders_list:
  path: /
  defaults: { _controller: controller.orders:indexAction }
  methods: [GET]

orders_create:
  path: /
  defaults: { _controller: controller.orders:createAction }
  methods: [POST]

orders_edit:
  path: /{id}
  defaults: { _controller: controller.orders:editAction }
  methods: [POST]

orders_remove:
  path: /{id}
  defaults: { _controller: controller.orders:removeAction }
  methods: [DELETE]

orders_view:
  path: /{id}
  defaults: { _controller: controller.orders:viewAction }
  methods: [GET]

orders_activate:
  path: /{id}/activate
  defaults: { _controller: controller.orders:activateAction }
  methods: [POST]

