AppBundle\Entity\Order:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            type: integer
            groups:
                - orders_index
                - orders_view
                - orders_create
        executionAt:
            expose: true
            type: DateTime<'Y-m-d'>
            groups:
                - orders_index
                - orders_view
                - orders_create
        active:
            expose: true
            type: boolean
            groups:
                - orders_index
