AppBundle\Entity\Product:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            type: integer
            groups:
                - product_index
                - basket_index
                - product_create
                - product_view
        name:
            expose: true
            type: string
            groups:
                - product_index
                - basket_index
                - order_list
                - product_create
                - product_view
        price:
            expose: true
            type: float
            groups:
                - product_index
                - basket_index
                - order_list
                - product_create
                - product_view
        description:
            expose: true
            type: string
            groups:
                - product_index
                - basket_index
                - product_create
                - product_view
        producent:
            expose: true
            type: AppBundle\Entity\Producent
            max_depth: 1
            groups:
                - product_index
                - basket_index
                - order_list
                - product_view
                - product_create
