AppBundle\Entity\Producent:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            type: integer
            groups:
                - producent_index
                - product_view
                - producent_view
        name:
            expose: true
            type: string
            groups:
                - product_index
                - basket_index
                - order_list
                - producent_index
                - producent_view
