AppBundle\Entity\Supplier:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            type: integer
            groups:
                - supplier_index
                - product_view
                - supplier_view
                - product_create
                - product_update
                - supplier_create
                - supplier_update

        name:
            expose: true
            type: string
            groups:
                - product_index
                - basket_index
                - order_list
                - supplier_index
                - supplier_view
                - product_create
                - product_view
                - product_update
                - supplier_create
                - supplier_update
