AppBundle\Entity\Basket:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            type: integer
            groups:
                - basket_index
        quantity:
            expose: true
            type: integer
            groups:
                - basket_index
        product:
            expose: true
            type: AppBundle\Entity\Product
            groups:
                - basket_index
