FoodCoopBundle\Entity\Product:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            type: integer
            groups:
                - product_index
                - basket_index
                - product_create
                - product_view
                - product_update
                - basket_create
        name:
            expose: true
            type: string
            groups:
                - product_index
                - basket_index
                - order_list
                - product_create
                - product_view
                - product_update
                - basket_create
        price:
            expose: true
            type: float
            groups:
                - product_index
                - basket_index
                - order_list
                - product_create
                - product_view
                - product_update
        description:
            expose: true
            type: string
            groups:
                - product_index
                - basket_index
                - product_create
                - product_view
                - product_update
        supplier:
            expose: true
            type: FoodCoopBundle\Entity\Supplier
            max_depth: 1
            groups:
                - product_index
                - basket_index
                - order_list
                - product_view
                - product_create
                - product_update
