<?php

namespace AppBundle\Entity;

use Codifico\Component\Actions\Repository\ActionRepositoryInterface;

/**
 * BasketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BasketRepository extends CriteriaAwareRepository implements ActionRepositoryInterface
{
}
